name: My first action

on: push

jobs:  
    first_job:
        runs-on: ubuntu-latest
        steps:
        -   name: Welcome
            run: echo "My first actions in 2024"

        -   name: List files
            run: ls

        -   name: Read file
            run: cat README.md