name: My first action

on: push

jobs:  
    first_job:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout repo
            uses: actions/checkout@v4
        -   name: Welcome
            run: echo "My first actions in 2024"

        -   name: List and read file
            run: |
                 echo "My first action job"
                 ls -ltra
                 cat README.md

        -   name: Generate ASCII Artwork
            run: cowsay -f dragon "Run for cover, I am a Dragon.....y echo fire diablo" >> dragon.txt